import { strict as assert } from "assert";
import dEI from "../dEI.js";

const { dEI_encode, dEI_decode } = dEI;
const verbose = process.argv.includes("--verbose");


/*
 * @author: AI
 * AI test slop generated by the cheapest model I could get my hands on.
 * Tests if dEI actually works for different test cases...
 * (don't stare at it too long or your brain will deteriorate over time) 
 */
function testRoundTrip(name, dt_d, suffix_d, mint_d, rarity_d, type_d, lvl_d, p_d, data) {
    try {
        const encoded = dEI_encode(dt_d, suffix_d, mint_d, rarity_d, type_d, lvl_d, p_d, data);
        const decoded = dEI_decode(encoded);

        if (verbose) {
            console.log(`\n${name}:`);
            console.log(`  Encoded: ${encoded}`);
            console.log(`  Date: ${dt_d} | Suffix: ${suffix_d} | Mint: ${mint_d} | Rarity: ${rarity_d}`);
            console.log(`  Type: ${type_d} | Level: ${lvl_d} | Percentile: ${p_d}`);
            console.log(`  Stats:`);
            data.forEach((s, i) => console.log(`    [${i}] ${s.name}: ${s.value}`));
        }

        assert.equal(decoded.creationDate, dt_d, `${name}: creationDate mismatch`);
        assert.equal(decoded.mint, mint_d, `${name}: mint mismatch`);
        assert.equal(decoded.rarity, rarity_d, `${name}: rarity mismatch`);
        assert.equal(decoded.type, type_d, `${name}: type mismatch`);
        assert.equal(decoded.suffix, suffix_d, `${name}: suffix mismatch`);
        assert.equal(decoded.upgradeLevel, lvl_d, `${name}: upgradeLevel mismatch`);
        assert.equal(decoded.percentile, p_d, `${name}: percentile mismatch`);
        assert.equal(decoded.stats.length, data.length, `${name}: stats length mismatch`);

        for (let i = 0; i < data.length; i++) {
            assert.equal(decoded.stats[i].name, data[i].name, `${name}: stat ${i} name mismatch`);
            const tolerance = (type_d === "gpu" && i === 0) ? 1e-8 : 0.01;
            assert(Math.abs(decoded.stats[i].value - data[i].value) < tolerance,
                `${name}: stat ${i} value mismatch (${decoded.stats[i].value} vs ${data[i].value})`);
        }

        console.log(`✓ ${name}`);
        return true;
    } catch (e) {
        console.error(`✗ ${name}: ${e.message}`);
        return false;
    }
}

console.log("\n=== dEI Encoding/Decoding Tests ===\n");

let passed = 0;
let failed = 0;

// CPU Tests (up to 5 stats)
if (testRoundTrip(
    "CPU 1-stat",
    "2024-01-15T00:00:00.000Z",
    "n00b",
    1,
    "D",
    "cpu",
    1,
    1,
    [
        { name: "Hack Damage", value: 50.0 }
    ]
)) passed++; else failed++;

if (testRoundTrip(
    "CPU 2-stat",
    "2024-01-15T00:00:00.000Z",
    "n3t",
    1,
    "D",
    "cpu",
    1,
    1,
    [
        { name: "Hack Damage", value: 42.5 },
        { name: "Hack Critical Damage Chance", value: 15.3 }
    ]
)) passed++; else failed++;

if (testRoundTrip(
    "CPU 3-stat",
    "2024-02-20T00:00:00.000Z",
    "Zypher",
    100,
    "C",
    "cpu",
    2,
    25,
    [
        { name: "Hack Damage", value: 75.0 },
        { name: "Hack Critical Damage Chance", value: 30.0 },
        { name: "True Damage", value: 20.0 }
    ]
)) passed++; else failed++;

if (testRoundTrip(
    "CPU 4-stat",
    "2024-03-15T00:00:00.000Z",
    "Macrohard",
    500,
    "B",
    "cpu",
    3,
    50,
    [
        { name: "Hack Damage", value: 250.0 },
        { name: "Hack Critical Damage Chance", value: 50.0 },
        { name: "True Damage", value: 75.0 },
        { name: "Hack Armor Penetration", value: 25.0 }
    ]
)) passed++; else failed++;

if (testRoundTrip(
    "CPU 5-stat (max)",
    "2024-10-01T00:00:00.000Z",
    "S3",
    50000,
    "B",
    "cpu",
    2,
    100,
    [
        { name: "Hack Damage", value: 999.99 },
        { name: "Hack Critical Damage Chance", value: 75.5 },
        { name: "True Damage", value: 25.0 },
        { name: "Hack Armor Penetration", value: 50.25 },
        { name: "Hack Critical Damage Bonus", value: 33.75 }
    ]
)) passed++; else failed++;

// GPU Tests (1-3 stats)
if (testRoundTrip(
    "GPU 1-stat",
    "2024-06-20T00:00:00.000Z",
    "Skynet",
    999,
    "S",
    "gpu",
    5,
    9,
    [
        { name: "Idle Crypto Mining", value: 0.00005 }
    ]
)) passed++; else failed++;

if (testRoundTrip(
    "GPU 2-stat",
    "2024-07-10T00:00:00.000Z",
    "GoGo",
    2000,
    "A",
    "gpu",
    4,
    60,
    [
        { name: "Idle Crypto Mining", value: 0.0001 },
        { name: "More Crypto Reward", value: 35.5 }
    ]
)) passed++; else failed++;

if (testRoundTrip(
    "GPU 3-stat (max)",
    "2024-05-15T00:00:00.000Z",
    "Zypher",
    5555,
    "B",
    "gpu",
    4,
    50,
    [
        { name: "Idle Crypto Mining", value: 0.0009999 },
        { name: "More Crypto Reward", value: 88.5 },
        { name: "Better Banter", value: 42.0 }
    ]
)) passed++; else failed++;

// PSU Tests (1 stat only)
if (testRoundTrip(
    "PSU 1-stat",
    "2023-12-01T00:00:00.000Z",
    "Meta",
    500,
    "B",
    "psu",
    3,
    10,
    [
        { name: "Crypto Mining Power", value: 45.75 }
    ]
)) passed++; else failed++;

if (testRoundTrip(
    "PSU max value",
    "2020-01-02T00:00:00.000Z",
    "Orange",
    1,
    "D",
    "psu",
    1,
    1,
    [
        { name: "Crypto Mining Power", value: 999.99 }
    ]
)) passed++; else failed++;

// Firewall/Router Tests (1-5 stats)
if (testRoundTrip(
    "Router 1-stat",
    "2025-01-10T00:00:00.000Z",
    "X",
    100,
    "C",
    "router",
    2,
    20,
    [
        { name: "Firewall Health", value: 150.0 }
    ]
)) passed++; else failed++;

if (testRoundTrip(
    "Router 2-stat",
    "2025-02-01T00:00:00.000Z",
    "chad",
    1500,
    "A",
    "router",
    5,
    75,
    [
        { name: "Firewall Health", value: 300.0 },
        { name: "Firewall Damage Reduction", value: 45.0 }
    ]
)) passed++; else failed++;

if (testRoundTrip(
    "Router 3-stat",
    "2025-03-05T00:00:00.000Z",
    "Orwell's",
    3000,
    "SS",
    "router",
    7,
    85,
    [
        { name: "Firewall Health", value: 500.0 },
        { name: "Firewall Damage Reduction", value: 25.5 },
        { name: "Firewall Regeneration", value: 10.25 }
    ]
)) passed++; else failed++;

if (testRoundTrip(
    "Router 4-stat",
    "2025-04-15T00:00:00.000Z",
    "Bug",
    8000,
    "S",
    "router",
    8,
    90,
    [
        { name: "Firewall Health", value: 750.0 },
        { name: "Firewall Damage Reduction", value: 50.0 },
        { name: "Firewall Regeneration", value: 35.0 },
        { name: "Firewall Advanced Encryption", value: 60.0 }
    ]
)) passed++; else failed++;

if (testRoundTrip(
    "Router 5-stat (max)",
    "2024-08-08T00:00:00.000Z",
    "Bug",
    12345,
    "A",
    "router",
    6,
    8,
    [
        { name: "Firewall Health", value: 999.99 },
        { name: "Firewall Damage Reduction", value: 75.5 },
        { name: "Firewall Regeneration", value: 45.25 },
        { name: "Firewall Advanced Encryption", value: 30.0 },
        { name: "Firewall Master Encryption", value: 60.75 }
    ]
)) passed++; else failed++;

// Edge cases
if (testRoundTrip(
    "GPU minimum value",
    "2024-02-14T00:00:00.000Z",
    "GG",
    1,
    "C",
    "gpu",
    1,
    1,
    [
        { name: "Idle Crypto Mining", value: 0.0000001 }
    ]
)) passed++; else failed++;

if (testRoundTrip(
    "Max mint number",
    "2023-06-10T00:00:00.000Z",
    "S1",
    100000,
    "SS",
    "cpu",
    10,
    100,
    [
        { name: "Hack Damage", value: 500.0 },
        { name: "Hack Critical Damage Chance", value: 60.0 }
    ]
)) passed++; else failed++;

if (testRoundTrip(
    "Max percentile",
    "2023-06-10T00:00:00.000Z",
    "S2",
    50000,
    "SSS",
    "cpu",
    10,
    100,
    [
        { name: "Hack Damage", value: 100.0 }
    ]
)) passed++; else failed++;

if (testRoundTrip(
    "All rarities - D",
    "2022-01-01T00:00:00.000Z",
    "n00b",
    1000,
    "D",
    "psu",
    1,
    1,
    [
        { name: "Crypto Mining Power", value: 10.0 }
    ]
)) passed++; else failed++;

if (testRoundTrip(
    "All rarities - SSS",
    "2026-09-30T00:00:00.000Z",
    "chad",
    50000,
    "SSS",
    "cpu",
    1,
    9,
    [
        { name: "Hack Damage", value: 999.99 },
        { name: "Hack Critical Damage Chance", value: 95.0 },
        { name: "True Damage", value: 50.5 }
    ]
)) passed++; else failed++;

// Avatar Tests
function testAvatarRoundTrip(name, type_d, rarity_d, mint_d, premium_d, expected_mint, dt_d) {
    try {
        const data = { premium: premium_d };
        const encoded = dEI_encode(dt_d, null, mint_d, rarity_d, type_d, null, null, data);
        const decoded = dEI_decode(encoded);
        const exp_mint = expected_mint !== undefined ? expected_mint : mint_d;

        if (verbose) {
            console.log(`\n${name}:`);
            console.log(`  Encoded: ${encoded}`);
            console.log(`  Date: ${dt_d} | Type: ${type_d} | Rarity: ${rarity_d} | Mint: ${mint_d} | Premium: ${premium_d}`);
        }

        assert.equal(decoded.type, type_d, `${name}: type mismatch`);
        assert.equal(decoded.rarity, rarity_d, `${name}: rarity mismatch`);
        assert.equal(decoded.mint, exp_mint, `${name}: mint mismatch`);
        assert.equal(decoded.premium, premium_d, `${name}: premium mismatch`);
        assert.equal(decoded.creationDate, dt_d, `${name}: creationDate mismatch`);

        console.log(`✓ ${name}`);
        return true;
    } catch (e) {
        console.error(`✗ ${name}: ${e.message}`);
        return false;
    }
}

console.log("\n=== Avatar Tests ===\n");

if (testAvatarRoundTrip(
    "Avatar basic (otter, common, mint 1, not premium)",
    "otter",
    "Common",
    1,
    false,
    undefined,
    "2024-01-15T00:00:00.000Z"
)) passed++; else failed++;

if (testAvatarRoundTrip(
    "Avatar premium flag",
    "trinity2",
    "Uncommon",
    100,
    true,
    undefined,
    "2024-02-20T00:00:00.000Z"
)) passed++; else failed++;

if (testAvatarRoundTrip(
    "Avatar high mint",
    "skynet",
    "Rare",
    999999,
    false,
    undefined,
    "2024-06-10T00:00:00.000Z"
)) passed++; else failed++;

if (testAvatarRoundTrip(
    "Avatar max rarity (Ethereal)",
    "nyancat",
    "Ethereal",
    50000,
    true,
    undefined,
    "2025-03-05T00:00:00.000Z"
)) passed++; else failed++;

if (testAvatarRoundTrip(
    "Avatar mid values",
    "hackergirl",
    "Epic",
    54321,
    false,
    undefined,
    "2024-08-01T00:00:00.000Z"
)) passed++; else failed++;

if (testAvatarRoundTrip(
    "Avatar mythic rarity",
    "gpt",
    "Mythic",
    1,
    false,
    undefined,
    "2023-12-25T00:00:00.000Z"
)) passed++; else failed++;

if (testAvatarRoundTrip(
    "Avatar invalid mint (too high) → -1",
    "foxgirl",
    "Legendary",
    1000000,
    true,
    -1,
    "2025-01-10T00:00:00.000Z"
)) passed++; else failed++;

if (testAvatarRoundTrip(
    "Avatar invalid mint (negative) → -1",
    "catgirl",
    "Common",
    -500,
    false,
    -1,
    "2023-06-01T00:00:00.000Z"
)) passed++; else failed++;

if (testAvatarRoundTrip(
    "Avatar invalid mint (zero) → -1",
    "lenia",
    "Uncommon",
    0,
    false,
    -1,
    "2026-09-01T00:00:00.000Z"
)) passed++; else failed++;

console.log(`\n=== Results ===`);
console.log(`Passed: ${passed}`);
console.log(`Failed: ${failed}`);
console.log(`Total:  ${passed + failed}\n`);

if (failed > 0) {
    process.exit(1);
}
